variables:
  ENV_NAME: $CI_COMMIT_BRANCH
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  CI_REGISTRY_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  ENVIRONMENT: "development"
  NODE_VERSION: "18"

#services:
#  - docker:dind
cache:
  paths:
    - ~/.npm/
    - ~/.nvm/
    - build/

stages:
  - build
  - deploy